routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['auth']], function(){
    Route::resource('post', 'PostController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title',
        'text',
        'publish_time',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('post.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());

          $post = new Post;
          $post->title = $request->title;
          $post->text = $request->text;
          $post->publish_time = $request->publish_time;
          $post->user_id = 1;
          $post->save();
        
        $post->save();
        return redirect()->route('post.index')->with('sucess','Novo post criado!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($post)
    {  
        $post = Post::find($post);
        //dd($post);
        return view('post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($post)
    {
        return view('post.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $post)
    {
        //dd($post);
        $post = Post::find($post);
        //dd($post);
        $post->title = $request->title;
        $post->text = $request->text;
        $post->publish_time = $request->publish_time;
        $post->user_id = 1;
        $post->save();
        return redirect()->route('post.index')->with('sucess','Novo post criado!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($post)
    {
        $post = Post::find($post);
        $post->delete();
        return redirect()->route('post.index')->with('sucess','Novo post criado!');

    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                        <li class="nav-item">
                                    <a class="nav-link" href="{{ route('post.index') }}">{{ __('posts') }}</a>
                                </li>
                            <li class="nav-item dropdown">
                                
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/post/_form.blade.php
<div class="form-group has-feedback {{ $errors->has('title') ? 'has-error' : '' }}">
    {{ Form::label('title', 'title*') }}
    {{ Form::text('title', null, ['class' => 'form-control', 'autofocus' => 'true', 'placeholder' => 'Digite seu nome completo', 'value' => $post->title ?? '']) }} 
    <span class="glyphicon glyphicon-user form-control-feedback"></span>
    @if ($errors->has('title'))
    <span class="help-block">
        <strong>{{ $errors->first('title') }}</strong>
    </span>
    @endif
</div>

<div class="form-group has-feedback {{ $errors->has('title') ? 'has-error' : '' }}">
    {{ Form::label('text', 'text*') }}
    {{ Form::text('text', null, ['class' => 'form-control', 'autofocus' => 'true', 'placeholder' => 'Digite seu nome completo', 'value' => $post->text ?? '']) }} 
    <span class="glyphicon glyphicon-user form-control-feedback"></span>
    @if ($errors->has('text'))
    <span class="help-block">
        <strong>{{ $errors->first('text') }}</strong>
    </span>
    @endif
</div>

<div class="form-group has-feedback {{ $errors->has('publish_time') ? 'has-error' : '' }}">
    {{ Form::label('publish_time', 'publish_time*') }}
    {{ Form::date('publish_time', null, ['class' => 'form-control', 'placeholder' => 'publish_time', 'value' => $post->publish_time ?? '']) }}
    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    @if ($errors->has('publish_time'))
    <span class="help-block">
        <strong>{{ $errors->first('publish_time') }}</strong>
    </span>
    @endif
</div>

resources/views/post/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="content">

        {!! Form::open(['route' => ['post.store'], 'method' => 'post', 'files' => true]) !!} 
        @include('post._form')
        {{ Form::submit('Criar post')}}
        {!! Form::close() !!}       

    </div>


@stop

resources/views/post/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="content">

        {!! Form::open(['route' => ['post.update', $post], 'method' => 'put', 'files' => true]) !!} 
        @include('post._form')
        {{ Form::submit('Editar Post')}}
        {!! Form::close() !!}

    </div>


@stop

resources/views/post/index.blade.php
@extends('layouts.app')

@section('css')
	<style>i.glyphicon-plus-sign{font-size:30px; padding-right: 5%;}</style>
@stop

@section('content')
<h1>Todas as postagens <a href="post/create"><i class="btn-primary btn glyphicon glyphicon-plus-sign pull-right">Create</i></a></h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">title</th>
            <th scope="col">text</th>
            <th scope="col">publish_time</th>
            <th width="5%" class="removesorting"></th>
            <th width="5%" class="removesorting"></th>
      
        </tr>
    </thead>
        <tbody class="table table-bordered table-striped">
            @foreach( $posts as $post )
                <tr>
                    <th scope="row">{{ $post->id }}</th>
                    <td>{{ $post->title }}</td>
                    <td>{{ $post->text }}</td>
                    <td>{{ $post->publish_time }}</td>
                    <td><a href="{{ route('post.show', $post->id) }}" class="btn btn-success">Read</a></td>
                    <td><a href="{{ route('post.edit', $post->id) }}" class="btn btn-primary">Update</a></td>
                    <td>
                        <form action="{{ route('post.destroy', $post->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
</table>

@stop

resources/views/post/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="content">

    <table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">title</th>
            <th scope="col">text</th>
            <th scope="col">publish_time</th>
            <th width="5%" class="removesorting"></th>
            <th width="5%" class="removesorting"></th>
      
        </tr>
    </thead>
        <tbody class="table table-bordered table-striped">

                <tr>
                    <th scope="row">{{ $post->id }}</th>
                    <td>{{ $post->title }}</td>
                    <td>{{ $post->text }}</td>
                    <td>{{ $post->publish_time }}</td>
                    <td><a href="{{ route('post.edit', $post->id) }}" class="btn btn-primary">Update</a></td>
                </tr>
        </tbody>
</table>

    </div>


@stop